service:
  name: serverless-sensor-app

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-reqvalidator-plugin
  - serverless-aws-documentation
  - serverless-dynamodb-local
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-1'}

  environment:
    SENSOR_TABLE: Sensors-${self:provider.stage}
    SENSOR_ID_INDEX: SensorIndex
    IS_OFFLINE: false
    IMAGES_S3_BUCKET: sensorlink-bucket-${self:provider.stage}
    SIGNED_URL_EXPIRATION: 300

  tracing:
    lambda : true
    apiGateway: true
    
custom:
  documentation:
    models:
      - name: CreateSensorRequest
        contentType: application/json
        schema: ${file(models/create-sensor-request.json)}
      - name: UpdateSensorRequest
        contentType: application/json
        schema: ${file(models/update-sensor-request.json)}
      

  serverless-offline:
    httpPort: 3003

  dynamodb:
    start:
      seed: true
      port: 8000
      inMemory: true
      migrate: true
    stages:
      - dev
    seed:
      todos:
        sources:
          - table: ${self:provider.environment.SENSOR_TABLE}
            sources: [./sensor.json]
       

functions:

  Auth:
    handler: src/lambda/auth/auth0Authorizer.handler

  GetSensors:
    handler: src/lambda/http/getSensors.handler
    events:
      - http:
          method: get
          path: sensors
          cors: true
          authorizer: Auth
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.SENSOR_TABLE}
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.SENSOR_TABLE}/index/${self:provider.environment.SENSOR_ID_INDEX}
      - Effect: Allow
        Action:
          - "xray:PutTraceSegments"
          - "xray:PutTelemetryRecords"
        Resource:
          - "*"


  CreateSensor:
    handler: src/lambda/http/createSensor.handler
    events:
      - http:
          method: post
          path: sensors
          cors: true
          reqValidatorName: RequestBodyValidator
          documentation:
            summary: Create a new sensor
            description: Create a new sensor
            requestModels:
              'application/json': CreateSensorRequest
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.SENSOR_TABLE}
      - Effect: Allow
        Action:
          - "xray:PutTraceSegments"
          - "xray:PutTelemetryRecords"
        Resource:
          - "*"
  
  UpdateSensor:
    handler: src/lambda/http/updateSensor.handler
    events:
      - http:
          method: patch
          path: sensors/{sensorId}
          reqValidatorName: RequestBodyValidator
          cors: true
          authorizer: Auth
          documentation:
            summary: Update a new sensor
            description: Update a new sensor
            requestModels:
              'application/json': UpdateSensorRequest
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
          - dynamodb:GetItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.SENSOR_TABLE}
      - Effect: Allow
        Action:
          - "xray:PutTraceSegments"
          - "xray:PutTelemetryRecords"
        Resource:
          - "*"
          
  DeleteSensor:
    handler: src/lambda/http/deleteSensor.handler
    events:
      - http:
          method: delete
          path: sensors/{sensorId}
          cors: true
          authorizer: Auth
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
          - dynamodb:GetItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.SENSOR_TABLE}
      - Effect: Allow
        Action:
          - "xray:PutTraceSegments"
          - "xray:PutTelemetryRecords"
        Resource:
          - "*"


  GenerateUploadUrl:
    handler: src/lambda/http/generateUploadUrl.handler
    events:
      - http:
          method: post
          path: sensors/{sensorId}/attachment
          cors: true
          authorizer: Auth
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
          - dynamodb:GetItem
        Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.SENSOR_TABLE}
      - Effect: Allow
        Action:
          - "xray:PutTraceSegments"
          - "xray:PutTelemetryRecords"
        Resource:
          - "*"
          
resources:
  Resources:
    # Add any necessary AWS resources
    SensorDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: sensorId
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: sensorId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.SENSOR_TABLE}
        LocalSecondaryIndexes:
          - IndexName: ${self:provider.environment.SENSOR_ID_INDEX}
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
              - AttributeName: createdAt
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

    RequestBodyValidator:
      Type: AWS::ApiGateway::RequestValidator
      Properties:
        Name: 'request-body-validator'
        RestApiId:
          Ref: ApiGatewayRestApi
        ValidateRequestBody: true
        ValidateRequestParameters: false

    AttachmentsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.IMAGES_S3_BUCKET}
        CorsConfiguration:
          CorsRules:
            -
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              MaxAge: 3000

    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        PolicyDocument:
          Id: MyPolicy
          Version: '2012-10-17'
          Statement:
            - Sid: PublicReadWriteBucketPolicy
              Effect: Allow
              Principal: '*'
              Action:
                - s3:GetObject
                - s3:PutObject
              Resource: arn:aws:s3:::${self:provider.environment.IMAGES_S3_BUCKET}/*
        Bucket: !Ref AttachmentsBucket